export const allItems =[
    {_id:101 , title:"All Categories"},
    {_id:102 , title:"Alexa Skills "},
    {_id:103 , title:"Amazon Devices"},
    {_id:104 , title:"Amazon Fashion"},
    {_id:105 , title:"Appliances"},
    {_id:106 , title:"Apps & Games"},
    {_id:107 , title:"Audible Audiobooks"},
    {_id:108 , title:"Baby"},
    {_id:109 , title:"Beauty"},
    {_id:110 , title:"Books"},
    {_id:111 , title:"Car & Motorbike"},
     {_id:112 , title:"Clothing Collection"},
    {_id:113 , title:"Computer & Accessorise"},
    {_id:114 , title:"Deals"},
    {_id:115 , title:"Electronic"},
    {_id:116 , title:"Funiture"},
]